#!/bin/bash

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "1.0.0"
    exit 0
fi

# optional argument handling
if [[ "$1" == "config" ]]
then
    echo "$KUBECONFIG"
    exit 0
fi

kured_brain_reboot="apiVersion: v1
kind: ConfigMap
metadata:
  name: kured-brain
  namespace: kube-system
data:
  state2: |-
    nodes=${2}
    value=reboot
    period=once
    scheduled=no
    timeFrame=\"\"
  
  nodeInProcess: \"\""

kured_brain_maint="apiVersion: v1
kind: ConfigMap
metadata:
  name: kured-brain
  namespace: kube-system
data:
  state2: |-
    nodes=${2}
    value=maintenance
    period=once
    scheduled=no
    timeFrame=\"\"
  
  nodeInProcess: \"\""

SetConfMap() {
if !( kubectl get configmaps -n kube-system | grep kured-brain ); then {
kubectl apply -f - <<EOF
${kured_brain_reboot}
EOF
}
fi
}

while getopts ":abc --reboot" opt; do
  case ${opt} in
    r | --reboot)       echo "REBOOT was triggered\n brain: ${kured_brain}"; SetConfMap ${kured_brain_reboot}
      ;;
    m | --maintenance)  echo "MAINTENANCE was triggered\n brain: ${kured_brain}"; SetConfMap ${kured_brain_maint}
      ;;
    v | --version)      echo "1.0.0"
                        exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
