apiVersion: v1
kind: ConfigMap
metadata:
#  creationTimestamp: 2017-12-27T18:36:28Z
  name: kured-brain
  namespace: kube-system
#  resourceVersion: "809965"
#  uid: d9d1ca5b-eb34-11e7-887b-42010a8002b8
data:
  state2: |-
    nodes=kind-worker2,kind-worker
    value=reboot
    period=once
    scheduled=no
    timeFrame=""
  
  nodeInProcess: ""